subjectsFile = open("TrainingData", "r")
subjects = subjectsFile.read()
subjects = subjects.replace("\n", " ")
subjects = (
    subjects.replace("0]", "")
    .replace("1]", "")
    .replace("2]", "")
    .replace("3]", "")
    .replace("4]", "")
    .replace("5]", "")
    .replace("6]", "")
    .replace("7]", "")
    .replace("8]", "")
    .replace("9]", "")
)
subjects = (
    subjects.replace("[0", "")
    .replace("[1", "")
    .replace("[2", "")
    .replace("[3", "")
    .replace("[4", "")
    .replace("[5", "")
    .replace("[6", "")
    .replace("[7", "")
    .replace("[8", "")
    .replace("[9", "")
    .replace("[", "")
    .replace("]", "")
)
subjects = subjects.replace("  "," ")
subjectsFile = open("TrainingData", "w")
subjectsFile.write(subjects)
subjectsFile.close()
